ebi-uniprot/uniprot-core

- controlled-vocabulary/src/main/java/uk/ac/ebi/uniprot/cv/disease/CrossReference.java
- controlled-vocabulary/src/main/java/uk/ac/ebi/uniprot/cv/disease/Disease.java
- controlled-vocabulary/src/main/java/uk/ac/ebi/uniprot/cv/disease/impl/DiseaseImpl.java
- controlled-vocabulary/src/main/java/uk/ac/ebi/uniprot/cv/impl/DiseaseFileReader.java
- controlled-vocabulary/src/main/java/uk/ac/ebi/uniprot/cv/keyword/impl/KeywordImpl.java
- core-domain/src/main/java/uk/ac/ebi/uniprot/domain/builder/DiseaseBuilder.java
- json-parser/src/main/java/uk/ac/ebi/uniprot/json/parser/JsonConfig.java
- json-parser/src/main/java/uk/ac/ebi/uniprot/json/parser/JsonUtils.java
- json-parser/src/main/java/uk/ac/ebi/uniprot/json/parser/disease/DiseaseJsonConfig.java
- json-parser/src/main/java/uk/ac/ebi/uniprot/json/parser/proteome/ProteomeJsonConfig.java
- json-parser/src/main/java/uk/ac/ebi/uniprot/json/parser/uniprot/UniprotJsonConfig.java
- json-parser/src/test/java/uk/ac/ebi/uniprot/json/parser/ValidateJson.java
- json-parser/src/test/java/uk/ac/ebi/uniprot/json/parser/disease/DiseaseTest.java
- json-parser/src/test/java/uk/ac/ebi/uniprot/json/parser/proteome/ProteinTest.java
- json-parser/src/test/java/uk/ac/ebi/uniprot/json/parser/proteome/ProteomeTest.java
- json-parser/src/test/java/uk/ac/ebi/uniprot/json/parser/uniprot/UniProtEntryIT.java
@LeonardoGonzales ,
Please review this as well. Part of same Jira TRM-22119
> TRM-22119 add proteincount, json confif and builder for disease model

- core-domain/src/main/java/org/uniprot/core/uniprot/builder/UniProtEntryBuilder.java
- core-domain/src/main/java/org/uniprot/core/uniprot/impl/UniProtEntryImpl.java
- core-domain/src/test/java/org/uniprot/core/uniprot/builder/UniProtEntryBuilderTest.java
- core-domain/src/test/java/org/uniprot/core/uniprot/impl/UniProtEntryImplTest.java
- core-parser/src/test/java/org/uniprot/core/parser/tsv/uniprot/comment/CommentTestUtil.java
- ff-parser/src/main/java/org/uniprot/core/flatfile/parser/impl/entry/EntryObjectConverter.java
- json-parser/src/test/java/org/uniprot/core/json/parser/uniprot/UniProtEntryIT.java
- tools-entry-scorer/src/test/java/org/uniprot/core/scorer/uniprotkb/comments/CCScoredTest.java
- tools-entry-scorer/src/test/java/org/uniprot/core/scorer/uniprotkb/comments/CommentScoreTestBase.java
- xml-parser/src/main/java/org/uniprot/core/xml/uniprot/UniProtEntryConverter.java
- xml-parser/src/test/java/org/uniprot/core/xml/uniprot/UniProtEntryConverterTest.java
Have a look and don't close the PR. I will use this same PR to merge the code once everything done
> Uniprot entry refactor

- core-domain/src/main/java/org/uniprot/core/citation/builder/AbstractCitationBuilder.java
- core-domain/src/main/java/org/uniprot/core/literature/LiteratureEntry.java
- core-domain/src/main/java/org/uniprot/core/literature/LiteratureStoreEntry.java
- core-domain/src/main/java/org/uniprot/core/literature/builder/LiteratureEntryBuilder.java
- core-domain/src/main/java/org/uniprot/core/literature/builder/LiteratureStoreEntryBuilder.java
- core-domain/src/main/java/org/uniprot/core/literature/impl/LiteratureEntryImpl.java
- core-domain/src/main/java/org/uniprot/core/literature/impl/LiteratureStoreEntryImpl.java
- core-domain/src/test/java/org/uniprot/core/ObjectsForTests.java
- core-domain/src/test/java/org/uniprot/core/literature/builder/LiteratureEntryBuilderTest.java
- core-domain/src/test/java/org/uniprot/core/literature/builder/LiteratureStoreEntryBuilderTest.java
- core-domain/src/test/java/org/uniprot/core/literature/impl/LiteratureEntryImplTest.java
- core-domain/src/test/java/org/uniprot/core/literature/impl/LiteratureStoreEntryImplTest.java
- core-parser/src/main/java/org/uniprot/core/parser/tsv/literature/LiteratureEntryMap.java
- core-parser/src/test/java/org/uniprot/core/parser/tsv/literature/LiteratureEntryMapTest.java
- json-parser/src/main/java/org/uniprot/core/json/parser/literature/LiteratureJsonConfig.java
- json-parser/src/test/java/org/uniprot/core/json/parser/literature/LiteratureEntryTest.java
- json-parser/src/test/java/org/uniprot/core/json/parser/literature/LiteratureStoreEntryTest.java
> Literature by protein

- core-domain/src/main/java/org/uniprot/core/uniprotkb/UniProtKBEntryType.java
- core-domain/src/test/java/org/uniprot/core/uniprotkb/UniProtKBEntryTypeTest.java
- json-parser/src/test/java/org/uniprot/core/json/parser/uniprot/UniprotKBEntryEnumTest.java
Code Change for TRM-23605 and TRM-23606 that are related
> update label for publication page

- core-domain/src/main/java/org/uniprot/core/uniprotkb/evidence/EvidenceCode.java
- core-domain/src/test/java/org/uniprot/core/uniprotkb/evidence/EvidenceCodeTest.java
https://www.ebi.ac.uk/panda/jira/browse/TRM-25326
> updated evidence code

- core-parser/src/main/java/org/uniprot/core/parser/tsv/proteome/ProteomeEntryValueMapper.java
- core-parser/src/test/java/org/uniprot/core/parser/tsv/proteome/ProteomeEntryValueMapperTest.java
add Proteome genome representation return field for TSV and JSON
> Proteome genome representation

- core-domain/src/main/java/org/uniprot/core/uniparc/UniParcEntry.java
- core-domain/src/main/java/org/uniprot/core/uniparc/impl/UniParcEntryImpl.java
- core-domain/src/test/java/org/uniprot/core/ObjectsForTests.java
- core-domain/src/test/java/org/uniprot/core/uniparc/impl/UniParcEntryBuilderTest.java
> add two new fields to keep min and max uniparc xref created and updated resp.

- ff-parser/src/main/java/org/uniprot/core/flatfile/parser/impl/cc/CcLineModelListener.java
- ff-parser/src/test/java/org/uniprot/core/flatfile/parser/integration/FlatfileRoundTripIT.java
- ff-parser/src/test/java/org/uniprot/core/flatfile/parser/integration/UniProtParserIT.java
- ff-parser/src/test/java/org/uniprot/core/flatfile/writer/line/cc/CCCatalyticActivityBuildTest.java
- ff-parser/src/test/resources/entryIT/P0DTC1.dat
fix catalytic activity FF parser missing molecule issue
> fix catalytic activity FF parser missing molecule issue

- core-parser/src/main/java/org/uniprot/core/parser/tsv/uniparc/UniParcEntryValueMapper.java
- core-parser/src/test/java/org/uniprot/core/parser/tsv/uniparc/UniParcEntryValueMapperTest.java
https://www.ebi.ac.uk/panda/jira/browse/TRM-26087
> make oldestCrossRefCreated and mostRecentCrossRefUpdated default return fields

- controlled-vocabulary/src/main/resources/META-INF/drlineconfiguration.json
- xml-parser/src/test/java/org/uniprot/core/xml/uniprot/UniProtKBCrossReferenceConverterTest.java
See https://www.ebi.ac.uk/panda/jira/browse/TRM-27012 for details.
> update xref property type with new names

- core-parser/src/main/java/org/uniprot/core/parser/tsv/disease/DiseaseEntryValueMapper.java
- core-parser/src/test/java/org/uniprot/core/parser/tsv/disease/DiseaseEntryValueMapperTest.java
See https://www.ebi.ac.uk/panda/jira/browse/TRM-26601 for details
> make result field stats consitent

- controlled-vocabulary/src/main/java/org/uniprot/cv/chebi/ChebiFileReader.java
- controlled-vocabulary/src/test/java/org/uniprot/cv/chebi/ChebiFileReaderTest.java
- core-domain/src/main/java/org/uniprot/core/cv/chebi/ChebiEntry.java
- core-domain/src/main/java/org/uniprot/core/cv/chebi/impl/ChebiEntryBuilder.java
- core-domain/src/main/java/org/uniprot/core/cv/chebi/impl/ChebiEntryImpl.java
- core-domain/src/test/java/org/uniprot/core/cv/chebi/impl/ChebiEntryBuilderTest.java
- core-domain/src/test/java/org/uniprot/core/cv/chebi/impl/ChebiEntryImplTest.java
Suggestion
- Add synonyms
- Add Chebi related Ids in the suggest as Well
Chebi Index
- load from rhea chebi.obo file 
- load extra relations from a tsv file
- load extra relationships from chebi file
> Chebi from rhea db

- ff-parser/src/main/antlr4/org/uniprot/core/flatfile/antlr/CcLineLexer.g4
- ff-parser/src/main/antlr4/org/uniprot/core/flatfile/antlr/CcLineParser.g4
- ff-parser/src/main/java/org/uniprot/core/flatfile/parser/impl/cc/CcLineModelListener.java
- ff-parser/src/test/java/org/uniprot/core/flatfile/antlr/CcLineBioPhyChemPCommentParserTest.java
fix biophyscochem property CC ff line parser contains curly bracket issue
> fix cc biophy ff parser

- controlled-vocabulary/src/main/resources/META-INF/drlineconfiguration.json
- controlled-vocabulary/src/test/java/org/uniprot/cv/xdb/UniProtKBDatabaseTypesTest.java
2022_02 new cross reference ClinGen
> add ClinGen cross reference

- ff-parser/src/main/java/org/uniprot/core/flatfile/parser/impl/ft/FTLineBuilderHelper.java
- ff-parser/src/test/java/org/uniprot/core/flatfile/writer/line/ft/FTVasplicFeatureBuildTest.java
ff writer write some tail-space that cause ff-parser failing
> ff writer remove trail space

- controlled-vocabulary/src/main/resources/META-INF/drlineconfiguration.json
TRM-28906: DEPOD url template out of date
TRM-28764: Fix link to some cross-reference databases
> Xref link fixes

- xml-parser/src/main/java/org/uniprot/core/xml/uniprot/LigandConverter.java
- xml-parser/src/test/java/org/uniprot/core/xml/uniprot/LigandConverterTest.java
This is one entry example with the issue: https://rest.uniprot.org/uniprotkb/K7N5M3.txt
> TRM-29271: Error parsing XML in 2023_01 release

- controlled-vocabulary/src/main/resources/META-INF/drlineconfiguration.json
> TRM-30227: Update TAIR URL template

- core-domain/src/main/java/org/uniprot/core/proteome/GenomeAssemblySource.java
- core-domain/src/test/java/org/uniprot/core/cv/xdb/UniProtKBDatabaseDetailTest.java
- core-domain/src/test/java/org/uniprot/core/proteome/GenomeAssemblySourceTest.java
See https://www.ebi.ac.uk/panda/jira/browse/TRM-30052 for details
> change the RefSeq case to use camelcase

- core-domain/src/main/java/org/uniprot/core/cv/xdb/UniProtDatabaseDetail.java
- core-parser/src/main/java/org/uniprot/core/parser/tsv/uniprot/EntryCrossReferenceMap.java
- core-parser/src/test/java/org/uniprot/core/parser/tsv/uniprot/EntryCrossReferenceMapTest.java
- core-parser/src/test/java/org/uniprot/core/parser/tsv/uniprot/UniProtKBEntryValueMapperTest.java
Adding comments in the Jira about implementation details
> Trm 28411 tsv xref

- ff-parser/src/main/antlr4/org/uniprot/core/flatfile/antlr/FtLineLexer.g4
- ff-parser/src/main/java/org/uniprot/core/flatfile/antlr/RememberLastTokenLexer.java
- ff-parser/src/main/java/org/uniprot/core/flatfile/parser/impl/ft/FtLineModelListener.java
- ff-parser/src/test/java/org/uniprot/core/flatfile/antlr/FtLineParserTest.java
https://www.ebi.ac.uk/panda/jira/browse/TRM-30725
> TRM-30725 fix var_seq sequence break bug

- controlled-vocabulary/src/main/resources/META-INF/drlineconfiguration.json
- controlled-vocabulary/src/test/java/org/uniprot/cv/xdb/UniProtKBDatabaseTypesTest.java
> remove xrefs

- controlled-vocabulary/pom.xml
- controlled-vocabulary/src/main/resources/META-INF/drlineconfiguration.json
- controlled-vocabulary/src/test/java/org/uniprot/cv/xdb/UniProtKBDatabaseTypesTest.java
- core-common/pom.xml
- core-domain-utils/pom.xml
- core-domain/pom.xml
- core-parser/pom.xml
- ff-parser/pom.xml
- jacoco-aggregate-report/pom.xml
- json-parser/pom.xml
- pom.xml
- tools-entry-scorer/pom.xml
- xml-parser/pom.xml
See TRM-32192 and TRM-31994 for details
> add a couple of xref for 2025_02

- core-parser/src/main/java/org/uniprot/core/parser/tsv/uniparc/UniParcSequenceFeatureMap.java
- core-parser/src/test/java/org/uniprot/core/parser/tsv/uniparc/UniParcSequenceFeatureMapTest.java
Jira for details https://embl.atlassian.net/browse/TRM-32773
> add null check for missing interpro group
